### ISSUE TITLE
Step 5.4.2 fails

### ISSUE THREAD

**Issue by vdmkenny** [ansible-lockdown/UBUNTU22-CIS#13]
When running the playbook (the devel branch) against ubuntu 22.04 server, I get the following:
```    
qemu.ubuntu22: TASK [ansible-lockdown.ubuntu22-cis : 5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Set faillock common-auth] ***
    qemu.ubuntu22: changed: [ubuntu22-test7-acceptance] => (item=***'regexp': 'auth\\s+required\\s+pam_faillock.so', 'line': 'auth    required            pam_faillock.so preauth', 'before': '^.*pam_unix.so'***)
    qemu.ubuntu22: changed: [ubuntu22-test7-acceptance] => (item=***'regexp': 'auth\\s+[default=die]\\s+pam_faillock.so', 'line': 'auth    [default=die]       pam_faillock.so authfail', 'after': '^.*pam_unix.so'***)
    qemu.ubuntu22: fatal: [ubuntu22-test7-acceptance]: FAILED! => ***"msg": "Incorrect sudo password"***
```
I'm running this in packer against a standard ubuntu iso. Previous versions (cis_release branch) seemed to work with the same configuration.
There is nothing configured, only extra allowed_sshd users.

**Comment by MrSteve81** [comment]
Thank you for raising this bug, I will see if i can replicate it today in testing.  As of now I have not been able to reproduce the error in my environment.

**Comment by vdmkenny** [comment]
I did use the devel branch.

**Comment by MrSteve81** [comment]
This was added to PR [#22] and is now in devel feel free to test out and let us know.

**Comment by binou-31** [comment]
Same error raised when applying this configure through SSH with sudo.
the only proper way i found is this one below, assuming that one line does not go without the other.
blockinfile module need to use marks to be idempotent, so staying with lineinfile did the same job like that

```yaml
      loop:
        - {
            regexp: 'auth\s+required\s+pam_faillock.so',
            line: "auth    required            pam_faillock.so preauth",
            before: "^.*pam_unix.so",
          }
        - {
            regexp: 'auth\s+[default=die]\s+pam_faillock.so\nauth\s+sufficient\s+pam_faillock.so',
            line: "auth    [default=die]       pam_faillock.so authfail\nauth    sufficient          pam_faillock.so authsucc",
            after: "^.*pam_unix.so",
          }
```
