### ISSUE TITLE
3.2.2 incorrect conditional causing opposite effect

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#139]
**Describe the Issue**
Incorrect conditional for the task causing ipv6 to remain enabled in the following task:
```
      - name: "3.2.2 | PATCH | Ensure IP forwarding is disabled | IPv6 settings"
        ansible.posix.sysctl:
            name: net.ipv6.conf.all.forwarding
            value: '0'
            sysctl_set: true
            state: present
            reload: true
            ignoreerrors: true
        notify:
            - Flush ipv6 route table
        when: ubtu22cis_ipv6_required
```

**Expected Behavior**
ipv6 should be disabled

**Actual Behavior**
ipv6 remaining enabled.

**Control(s) Affected**
3.2.2

**Additional Notes**
Anything additional goes here

**Possible Solution**
Add a `not` in front of the conditional. `when: not ubtu22cis_ipv6_required`
