### ISSUE TITLE
3.5.1.x UFW not disabling nftables

### ISSUE THREAD

**Issue by zac90** [ansible-lockdown/UBUNTU22-CIS#143]
**Describe the Issue**
If ufw is enabled, both iptables and nftables should be removed. At the moment only `iptables-persistent` is removed. Ensure nftables is also purged as some files persist with a normal remove.

**Expected Behavior**
Remove nftables as well

**Actual Behavior**
nftables remains with ufw active and may cause unexpected results.

**Control(s) Affected**
3.5.1.x and 3.5.3.1.2

**Additional Notes**
The CIS Hardening guide does not specifically state to do this in the ufw section however at the start of the firewall overview it contains the following "Only one method should be used to configure a firewall on the system. Use of more than one method could produce unexpected results"

**Possible Solution**
Add the following to remove nftables when ufw is in use. Similar to control 3.5.3.1.2, except both that control and this one should use the `apt` module with `purge: true`
```
- name: "Ensure nftables is uninstalled when using ufw"
  apt:
      name: nftables
      purge: true     
      state: absent
```
