### ISSUE TITLE
5.4.1 | PATCH | Ensure password creation requirements are configured

### ISSUE THREAD

**Issue by ma3s7ro** [ansible-lockdown/UBUNTU22-CIS#182]
## Feature Request or Enhancement

- Enhancement

**Summary of Request**
Change pwquality settings using variables. In our organization more securely requirements.

**Describe Alternatives You've Considered**
Add variable in default and change play. This will allow you to flexibly configure pwquality

**Suggested Code**
Add variable in default.
```
ubtu22cis_pwquality:
  - key: 'minlen'
    value: '14'
   - key: 'minclass'
    value: '5'
  - key: 'dcredit'
    value: '-1'
  - key: 'ucredit'
    value: '-1'
  - key: 'ocredit'
    value: '-1'
  - key: 'lcredit'
    value: '-1'

```
Change play:
```
     - name: "5.4.1 | PATCH | Ensure password creation requirements are configured"
        lineinfile:
            state: present
            create: yes
            dest: /etc/security/pwquality.conf
            regexp: '^{{ item.key }}'
            line: '{{ item.key }} = {{ item.value }}'
        with_items:
            - "{{ ubtu22cis_pwquality }}"
```
