### ISSUE TITLE
Tasks are not being skipped based on defaults/main.yml or passing '-e taskname=false'

### ISSUE THREAD

**Issue by mboeker** [ansible-lockdown/UBUNTU22-CIS#229]
**Describe the Issue**
I am trying to run the playbook with certain components skipped. For example NetworkManager, I don't want that installed. I tried both of these options:
`ubtu22cis_install_network_manager: false`
in defaults/main.yml, and
`ansible-playbook -e ubtu22cis_install_network_manager=false site.yml`
but it is still installing it. Same with rule 5.3.4, sudo password. Even when I set `ubtu22cis_rule_5_3_4: false` and pass `-e ubtu22cis_rule_5_3_4=false` it sets a sudo password.

**Expected Behavior**
Tasks get skipped if defaults/main.yml or -e args are set to false.

**Actual Behavior**
Tasks are still processed.

**Control(s) Affected**
Hardening process

**Environment (please complete the following information):**

- branch being used: main
- Ansible Version: ansible 9.5.1 from pip3
- Host Python Version: 3.10.12
- Ansible Server Python Version: 3.10.12
- Additional Details: Ubuntu 22.04 from Jan 2024.

**Additional Notes**
When I change the playbooks to explicitly check for `bool` they work as expected.
So this task, in prelim.yml:
```
- name: "PRELIM | PATCH | Install Network-Manager"
  ansible.builtin.package:
      name: network-manager
      state: present
  when:
      - ubtu22cis_rule_3_1_2
      - ubtu22cis_install_network_manager
      - not system_is_container
      - "'network-manager' not in ansible_facts.packages"
  tags:
      - always
```
That will install network manager no matter what is set in defaults/main.yml or passed as an arg. HOWEVER, if I change the task to this, appending `| bool` to ubtu22cis_install_network_manager:
```
- name: "PRELIM | PATCH | Install Network-Manager"
  ansible.builtin.package:
      name: network-manager
      state: present
  when:
      - ubtu22cis_rule_3_1_2
      - ubtu22cis_install_network_manager | bool  # force checking if true/false
      - not system_is_container
      - "'network-manager' not in ansible_facts.packages"
  tags:
      - always
```
then it will skip the task if I set the variable in defaults/main.yml or pass the argument.

**Possible Solution**
See notes.
